# Generated by Django 2.2.5 on 2019-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_num', models.TextField(max_length=255, verbose_name='Введенная цифра')),
                ('out_num', models.TextField(max_length=255, verbose_name='Конвертированная цифра')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
