# Generated by Django 2.2.5 on 2019-09-15 08:20

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='date',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
