# Generated by Django 2.2.5 on 2019-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20190915_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата время'),
        ),
    ]
